---
- name: Prepare
  hosts: all
  gather_facts: no

  collections:
  - jabdr.sql_query

  tasks:
  - name: Install dependencies
    dnf:
      name:
      - python3-sqlalchemy
      - sqlite
  - name: Create test database
    command: sqlite3 /test.db
    args:
      stdin: "{{lookup('file', 'testdb.sql') }}"
